export const navigation = {
  public: [
    { label: "Home", href: "/" },
    { label: "About", href: "/about" },
    { label: "Book My Ride", href: "/book-my-ride" },
    { label: "Drive With Us", href: "/drive-with-us" },
    { label: "Partners", href: "/partners" },
    { label: "Help", href: "/help" },
    { label: "Login", href: "/login" },
  ],
  rider: [
    { label: "Book", href: "/rider/book" },
    { label: "History", href: "/rider/history" },
    { label: "Profile", href: "/rider/profile" },
    { label: "Dashboard", href: "/rider/dashboard" },
  ],
  driver: [
    { label: "Dashboard", href: "/driver/dashboard" },
    { label: "Manifest", href: "/driver/manifest" },
    { label: "Shift", href: "/driver/shift" },
    { label: "Earnings", href: "/driver/earnings" },
    { label: "Wallet", href: "/driver/wallet" },
    { label: "Incentives", href: "/driver/incentives" },
    { label: "Ratings", href: "/driver/ratings" },
    { label: "Vehicle", href: "/driver/vehicle" },
    { label: "Documents", href: "/driver/documents" },
    { label: "Support", href: "/driver/support" },
    { label: "Preferences", href: "/driver/preferences" },
  ],
  agent: [
    { label: "Dashboard", href: "/agent/dashboard" },
    { label: "Bookings", href: "/agent/bookings" },
    { label: "Travel Plans", href: "/agent/plans" },
    { label: "Live Operations", href: "/agent/live-operations" },
    { label: "Roster", href: "/agent/roster" },
    { label: "Clients", href: "/agent/clients" },
    { label: "Bulk Upload", href: "/agent/bulk-upload" },
    { label: "Billing", href: "/agent/billing" },
    { label: "Reports", href: "/agent/reports" },
    { label: "Data Hub", href: "/agent/data-hub" },
    { label: "Help Center", href: "/agent/help-center" },
    { label: "Partners", href: "/agent/partners" },
  ],
  admin: [
    { label: "Dashboard", href: "/admin/dashboard" },
    { label: "Dispatch", href: "/admin/dispatch" },
    { label: "Users", href: "/admin/users" },
    { label: "Driver Enrollments", href: "/admin/enrollments" },
    { label: "CRM", href: "/admin/crm" },
    { label: "Client History", href: "/admin/trips-history" },
    { label: "Billing", href: "/admin/billing" },
    { label: "Payments", href: "/admin/payments" },
    { label: "Reviews", href: "/admin/reviews" },
    { label: "Reports", href: "/admin/reports" },
    { label: "Agent Review", href: "/admin/agents" },
    { label: "Compliance", href: "/admin/compliance" },
    { label: "Settings", href: "/admin/settings" },
  ],
} as const;

export type RoleType = Exclude<keyof typeof navigation, "public">;
